// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dufbtyqoxhhpomgirrsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1ZmJ0eXFveGhocG9tZ2lycnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNzY4NzQsImV4cCI6MjA3Njc1Mjg3NH0.RsyZ-LUq1WCiKHVTo4ZHx_dmyczFvMtGOFkeUY-p_zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});